version: "2"
services:
  zeebe:
    container_name: zeebe
    image: camunda/zeebe:0.26.1
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
    depends_on:
      - elasticsearch
    volumes:
      - rzd_zeebe_data:/usr/local/zeebe/data
      - ../volumes/zeebe-standalone-application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - rzd_network
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.14
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    volumes:
      - rzd_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - rzd_network
  operate:
    container_name: operate
    image: camunda/operate:0.26.0
    ports:
      - "8080:8080"
    depends_on:
      - zeebe
      - elasticsearch
    volumes:
      - ../volumes/operate-application.yml:/usr/local/operate/config/application.yml
    networks:
      - rzd_network
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana-oss:6.8.14
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - rzd_network
#  elasticsearch-head:
#    container_name: elasticsearch-head
#    image: mobz/elasticsearch-head:5
#    environment:
#      - TZ=Asia/Shanghai
#    ports:
#      - "9100:9100"
#    volumes:
#      - ../volumes/elasticsearch-head-vendor.js:/usr/src/app/_site/vendor.js
#    depends_on:
#      - elasticsearch
#    networks:
#      - rzd_network

volumes:
  rzd_zeebe_data:
  rzd_elasticsearch_data:

networks:
  rzd_network:
    driver: bridge
